version: '3.1'
services:

  postgres_db:
    image: postgres:10.4
    container_name: postgres_db
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: estoque
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [ backend-net ]

  backend:
    container_name: server-api
    image: node:10-slim
    working_dir: "/usr/current/app/src"
    command: ./start.sh
    environment:
      WAIT_HOSTS: postgres_db:5432
      PG_DATABASE: postgres_db
    volumes:
      - .:/usr/current/app/src:rw
    ports: [ "3333:3333" ]
    networks: [ backend-net ]
    links: [ postgres_db ]

networks:
    backend-net:
